services:
  backend:
    build:
      context: ./HotelBookUP-Back-End
    container_name: backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal\SQLEXPRESS;Database=HotelBookingDB;Trusted_Connection=True;TrustServerCertificate=True;MultipleActiveResultSets=True;
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./HotelBookUP-frontend/HotelBookUP-frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
