services:
  backend:
    build:
      context: ./HotelBookUP-Back-End
    container_name: backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5259
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal,1433;Database=HotelBookingDB;User ID=Admin;Password=1505;TrustServerCertificate=True;MultipleActiveResultSets=True;
    ports:
      - "5259:5259"

  frontend:
    build:
      context: ./HotelBookUP-frontend/HotelBookUP-frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    env_file:
      - ./HotelBookUP-frontend/HotelBookUP-frontend/.env 
